# container-based build
sudo: false

language: scala

# These directories are cached to S3 at the end of the build
cache:
  directories:
   - $HOME/.m2
   - $HOME/.ivy2
   - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION

scala:
  - 2.11.8

jdk:
  - oraclejdk8

script:
  - git config --local user.email "scf370@gmail.com"
  - git config --local user.name "Travis"
  - sbt ++$TRAVIS_SCALA_VERSION coverage test
  - cat .secret-enc/.credentials | openssl aes-256-cbc -a -d -k "$PASSWORD" > ~/.bintray/.credentials
  - sbt dist
  - eval "$(ssh-agent -s)" #start the ssh agent
  - cat .secret-enc/github_key | openssl aes-256-cbc -a -d -k "$PASSWORD" > github_key
  - chmod 600 github_key
  - ssh-add github_key
  - git remote add deploy git@github.com:scf37/config2.git
  - git branch -f master HEAD
  - git checkout master
  - git status
  - git push deploy master

after_success:
  - sbt ++$TRAVIS_SCALA_VERSION coverageReport coveralls

